### ISSUE TITLE
Merge docs into repo

### ISSUE THREAD

**Issue by Ocramius** [samrap/gestalt#18]
Having docs splitted out is plain confusing - merge with the main repo?

**Comment by samrap** [comment]
The point of having the docs separate is because when I officially release this package I'll have a website that will pull the docs using the GitHub API. I don't want them in this repo because it doesn't make sense to pull them down on every `composer update/install`. I think with a couple code examples in the readme, it will make more sense.

**Comment by Ocramius** [comment]
You'd just provide a .gitattributes file for that ;-)
