### ISSUE TITLE
Propagate changes to config file when 'set' or 'add' are called. 

### ISSUE THREAD

**Issue by nathan-fiscaletti** [samrap/gestalt#5]
When making changes to the config object, it would be nice if they could automatically be saved to file. If this feature were to be implemented, it would also be nice if there were some sort of a configuration variable that would allow for this feature to be turned off, and instead a `->save()` function to be used.

**Comment by samrap** [comment]
I like the idea of persisting changes but due to the nature of this package, it is impossible to define a single way to save the configuration values. Please open a new issue requesting the implementation of the observer pattern, as that would allow the user to define how the changes should be saved by adding custom listeners to the Configuration object.
